[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_PUBLIC_BUILD_ID = "v4.0.0-$(date +%s)"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"
